### ISSUE TITLE
Automated tests for parsers

### ISSUE THREAD

**Issue by fmaguire** [pha4ge/hAMRonization#19]
Tests need implemented for new parsers

**Comment by cimendes** [comment]
I think this was also assigned to me?

**Comment by fmaguire** [comment]
Don't worry too much about tight integration with code, just automated functional tests (i.e. known input == expected output) for each of the parsers for now. 

I'll modify them to use the refactored parser library later on

**Comment by cimendes** [comment]
parser output tests:
- [ ] abricate 
- [ ] amrfinder
- [ ] amrplusplus
- [ ] ariba
- [ ] deepARG
- [ ] groot
- [ ] kmerresistance
- [ ] ~~mykrobe~~
- [ ] ~~pointfinder~~
- [ ] resfams
- [ ] resfinder
- [ ] rgi
- [ ] srax
- [ ] srst2
- [ ] c-sstar
- [ ] staramr

**Comment by fmaguire** [comment]
Great work so far @cimendes!
