### ISSUE TITLE
Dummy one-hit output for each tool

### ISSUE THREAD

**Issue by fmaguire** [pha4ge/hAMRonization#25]
Generate a single same hit in each tool's format for a simple test-case

**Comment by cimendes** [comment]
Dummy outputs:
- [ ] abricate 
- [ ] amrfinder
- [ ] amrplusplus
- [ ] ariba
- [ ] deepARG
- [ ] groot
- [ ] kmerresistance
- [ ] mykrobe
- [ ] pointfinder
- [ ] resfams
- [ ] rgi
- [ ] srax
- [ ] srst2
- [ ] sstar
- [ ] ataramr
