### ISSUE TITLE
Extend schema(s) to include point mutation info

### ISSUE THREAD

**Issue by dfornika** [pha4ge/hAMRonization#4]
Our schemas currently only incorporate resistance gene detection information, but don't include fields that are relevant to point mutations. Point mutations (and other variants like indels) are important mechanisms of antibiotic resistance and several of our tools include that type of information in their output.

Gene detection information was incorporated first because it was generally deemed to be simpler and more consistent than point mutations, but our schema should support both types of information.

**Comment by cimendes** [comment]
Addressed in #60
