### ISSUE TITLE
AMRfinder aminoacid reference lenght being saved in gene lenght field

### ISSUE THREAD

**Issue by cimendes** [pha4ge/hAMRonization#42]
The `amrfinder` parsers are saving the aminoacid reference lenght in the `reference_gene_lenght` field

**Comment by fmaguire** [comment]
the amrfinderplus parser should save query amino acid length to `input_protein_length` if run using proteins or query gene length to `input_gene_length` if using gene as query.

Does this look ok?

**Comment by cimendes** [comment]
You're right. I put a silly value on my [dummy file](https://github.com/pha4ge/hAMRonization/blob/master/test/dummy/amrfinder/report.tsv). Parser is working as intended! Sorry for the confusion!
