### ISSUE TITLE
Testing: flake8 linting shows errors & warnings but workflow step doesn't fail

### ISSUE THREAD

**Issue by dfornika** [pha4ge/hAMRonization#5]
As part of our testing suite, we run `flake8` against the parsers and the `AntimicrobialResistanceGenomicAnalysisResult` class, using GitHub Actions.

We can see in the logs that `flake8` is finding issues, but the workflow steps are passing anyways. See:

https://github.com/pha4ge/harmonized-amr-parsers/runs/546839506?check_suite_focus=true#step:4:23

The linting workfow steps should fail if there are linting issues.

**Comment by dfornika** [comment]
I just noticed this note that explains why the linting step doesn't cause the workflow to fail. It is explicitly made to exit with status 0.

https://github.com/pha4ge/harmonized-amr-parsers/blob/4397bbfff73818776b1787bcd14e55a93f70921a/.github/workflows/pythonpackage.yml#L32

**Comment by fmaguire** [comment]
Refactor is now flake8 compliant too.
