### ISSUE TITLE
Wrong Docker link

### ISSUE THREAD

**Issue by iaconogi** [pha4ge/hAMRonization#53]
Dear Finley,
I am Giovanni Iacono from EFSA, we had a video call the other day.
The compilation of the Dockerfile from https://github.com/pha4ge/hAMRonization_workflow **fails** at task 18 RUN cd data/test && bash get_test_data.sh && cd ../..

**The reason** is that in the current repository https://github.com/pha4ge/hamronization the data folder is not present. This folder is present in https://github.com/pha4ge/hAMRonization_workflow.

Also a question, the Dockerfile in https://github.com/pha4ge/hAMRonization_workflow installs only the parsers, correct ?

**Comment by fmaguire** [comment]
To install just the parsers in this repo you can now just run `docker pull finlaymaguire/hamronization:latest` and it will just install a minimal container with the python3.9 base image and `hamronize` as the entrypoint.

Let me know if you have any issues with the container.

**Comment by iaconogi** [comment]
Yes I already did a minimal container  with pyhton and pip install hamronization and it works great so far.
Best
Giovanni
