### ISSUE TITLE
ORF_ID missing once RGI report hAMRonized

### ISSUE THREAD

**Issue by SvetlanaUP** [pha4ge/hAMRonization#58]
Hi Finlay,

when running ORFs through the RGI-hARMonization pipeline, the ORF_ID (important for final hAMR report) is skipped.

Here https://github.com/SvetlanaUP/hAMRonization/blob/master/hAMRonization/RgiIO.py
you can see that I fixed ORF_ID self.field_mapping manually (Fixed 'ORF_ID': 'None', 'Contig': 'input_sequence_id' (should be opposite) ).

This solution works for us, but maybe for the future would be good to have it defined in the RgiIO.py, e.g. if there is no 'Contig' use 'ORF_ID'.

Thanks,
Svetlana

**Comment by fmaguire** [comment]
Ah yes, good catch, should add a conditional and a test set for RGI in ORF mode. @raphenya you totally swamped right now or would you have a chance to add that?
