### ISSUE TITLE
Genetic_variation_type

### ISSUE THREAD

**Issue by jodyphelan** [pha4ge/hAMRonization#65]
At the moment the 'variant type' is set as non- mandatory but probably should be made mandatory. This attribute was added as part of the introduction of variant spec
    https://github.com/pha4ge/hAMRonization/blob/ee85f6de0e43ffb0b8ab3da2387edb2c5ddfbe3e/hAMRonization/hAMRonizedResult.py#L25

**Comment by cimendes** [comment]
Addressed in #60 
genetic_variation_type is now a required field in the latest version of the spec
