### ISSUE TITLE
PyPi not updated, 1.0.4 tarball reports version 1.0.3

### ISSUE THREAD

**Issue by jfy133** [pha4ge/hAMRonization#78]
Hello,

We are using haAMRonization in a pipeline ([nf-core/funcscan](https://github.com/nf-core/funcscan)), and I saw there was a new version of the tool so I went to update it in our pipeline.

However when I went to do so, I saw the update wasn't on bioconda, and when I tired up update the recipe - the CI test failed saying that 1.0.4 doesn't exist on pypi.

Secondly, when I went to build the package locally myself from the tarball under the releases page, I've saw that if I run `hamronization --version` it still reports 1.0.4. 

It would be maybe good to have a release update with the correct version

(or ideally, if possible 1.0.5 and a fix #66 included. I would try to contribute this myself as it doesn't seem complicated but I'm not a python dev unfortunately)

**Comment by fmaguire** [comment]
Thanks for the PR and your interest! 
This should now be resolved with version 1.1.0 is available on pypi and conda to follow shortly.
v1.1.0 should address the empty report issue and add fARGene support for the retrieve gene output files (which I believe was also requested for use in funcscan). Sorry for how long this took!

**Comment by jfy133** [comment]
Absolutely no worries, actually I would argue this is a fast response ;)! I'll monitor the bioconda recipe and ask for a bump if neccessary on the bioconda recipe. Thank you!
