### ISSUE TITLE
[BUG] Generated output does not follow CSP rules

### ISSUE THREAD

**Issue by remimestdagh** [pha4ge/hAMRonization#81]
**Describe the bug**
The generated output HTML uses inline JavaScript code. This is a violation of CSP rules.

**Input**
Any input

**Input file**
Any

**Error log**
NA

**hAMRonization Version**
NA

**Expected behavior**
The generated output file follows CSP rules.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] any
 - Browser [e.g. chrome, safari] any
 - Version [e.g. 22] any

**Comment by fmaguire** [comment]
I can't really see a way to make this compliant without losing the benefit of having a self-contained HTML file that can be shared.  Feel free to make a PR if you have a good solution!
