### ISSUE TITLE
software and reference version

### ISSUE THREAD

**Issue by MPC21** [pha4ge/hAMRonization#89]
How to get the version of analysis software and reference database as they seem compulsory when using hAMRonization?
--analysis_software_version ANALYSIS_SOFTWARE_VERSION                      
--reference_database_version REFERENCE_DATABASE_VERSION

**Comment by fmaguire** [comment]
Hi @MPC21 those versions refer to whichever supported AMR annotation tool you are running.

For example, if amrfinderplus:

- `--analysis_software_version` can be found by running `amrfinder --version` 

- `--reference_database_version` can be found in the output when you run amrfinder

or for rgi:

- `--analysis_software_version` can be found by running `rgi main --version` 

- `--reference_database_version` can be found by running `rgi database --version`
