### ISSUE TITLE
hAMRonization usage for rgi and AMRFinderPlus

### ISSUE THREAD

**Issue by rl-13** [pha4ge/hAMRonization#90]
Hi,

I successfully ran hAMRonization using ABRicate outputs. Yet, I tried using hAMRonization for rgi and AMRFinderPlus outputs, and encountered problems. What should I put for the report and input_file_name options? Are they the same?

Here is the code I used:

hamronize rgi --report rgi_out.txt --analysis_software_version "v6.0.3" --reference_database_version "XXXXX"

Thank you very much!

**Comment by fmaguire** [comment]
Hi @rl-13, 

`input_file_name` is a way to add a metadata field that helps you work out what file the underlying AMR tool (i.e., RGI in your case) was actually run on.  This could be something like "my_genome_32.fasta".   This is important when you are combining lots of reports and many tools don't include this information in their output reports.

`report` is a positional argument that you give the path to the AMR tool output file (i.e., RGI's output)
